#!/usr/bin/env bash
# This script iterate 1-20 and then bad luck from China for the 4th loop iteration 9 and then bad luck from Japan for the 9th loop iteration  17 and then bad luck from Italy for the 17th loop iteration

COUNT=1
while [ $COUNT -le 20 ];
do

case $COUNT in

4)
echo "$COUNT" && echo "bad luck from China";;
9)
echo  "$COUNT" && echo "bad luck from Japan";;
17)
echo "$COUNT" && echo "bad luck from Italy";;
*)
echo "$COUNT";;
esac
COUNT=$((COUNT+1))
done
